#Name of workflow
name: 'linter and tests'

#Trigger the workflow on push or pull request
on:
  - push
env:
  CI: true

jobs:
  build:

    #The type of machine to run the job on
    runs-on:  ubuntu-latest

    strategy:
      #Node version list
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: npm install
      run: |
        make install
    - name: Run linter
      run: |
        make lint
    - name: Test code coverage
      run: | 
        make test
    - name: Test & publish code coverage
      # https://github.com/paambaati/codeclimate-action
      uses: paambaati/codeclimate-action@v3.0.0
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID : ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
          coverageCommand: make test-coverage
